import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "🍚 함께 나누는 따뜻한 식생활",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className="w-full mx-auto max-w-[var(--space-mobileMax)]">
					{children}
				</div>
			</body>
		</html>
	);
}
